function JB = ContactJacobianB(x,y,phi,alphaF,lF,alphaB,lB,l1,l2,l3,rFoot,g,m1,m2,m3,j1,j2,j3)
%CONTACTJACOBIANB
%    JB = CONTACTJACOBIANB(X,Y,PHI,ALPHAF,LF,ALPHAB,LB,L1,L2,L3,RFOOT,G,M1,M2,M3,J1,J2,J3)

%    This function was generated by the Symbolic Math Toolbox version 5.4.
%    10-Apr-2011 10:49:22

t684 = alphaB+phi;
t685 = cos(t684);
t686 = lB.*t685;
t687 = sin(t684);
t688 = lB.*t687;
JB = reshape([1.0,0.0,0.0,1.0,rFoot+t686+l1.*sin(phi),t688-l1.*cos(phi),0.0,0.0,0.0,0.0,rFoot+t686,t688,t687,-t685],[2, 7]);
