function dJBdtTIMESdqdt = ContactJacobianBDtTIMESdqdt(x,y,phi,alphaF,lF,alphaB,lB,dx,dy,dphi,dalphaF,dlF,dalphaB,dlB,l1,l2,l3,rFoot,g,m1,m2,m3,j1,j2,j3)
%CONTACTJACOBIANBDTTIMESDQDT
%    DJBDTTIMESDQDT = CONTACTJACOBIANBDTTIMESDQDT(X,Y,PHI,ALPHAF,LF,ALPHAB,LB,DX,DY,DPHI,DALPHAF,DLF,DALPHAB,DLB,L1,L2,L3,RFOOT,G,M1,M2,M3,J1,J2,J3)

%    This function was generated by the Symbolic Math Toolbox version 5.4.
%    10-Apr-2011 10:49:23

t697 = alphaB+phi;
t698 = sin(t697);
t699 = cos(t697);
t700 = dalphaB.*lB.*t698;
t701 = dlB.*t698;
t702 = dalphaB.*lB.*t699;
dJBdtTIMESdqdt = [-dalphaB.*(t700-dlB.*t699+dphi.*lB.*t698)+dlB.*(dalphaB.*t699+dphi.*t699)-dphi.*(t700+dphi.*(lB.*t698-l1.*cos(phi))-dlB.*t699);dphi.*(t701+t702+dphi.*(lB.*t699+l1.*sin(phi)))+dlB.*(dalphaB.*t698+dphi.*t698)+dalphaB.*(t701+t702+dphi.*lB.*t699)];
