function dJFdtTIMESdqdt = ContactJacobianFDtTIMESdqdt(x,y,phi,alphaF,lF,alphaB,lB,dx,dy,dphi,dalphaF,dlF,dalphaB,dlB,l1,l2,l3,rFoot,g,m1,m2,m3,j1,j2,j3)
%CONTACTJACOBIANFDTTIMESDQDT
%    DJFDTTIMESDQDT = CONTACTJACOBIANFDTTIMESDQDT(X,Y,PHI,ALPHAF,LF,ALPHAB,LB,DX,DY,DPHI,DALPHAF,DLF,DALPHAB,DLB,L1,L2,L3,RFOOT,G,M1,M2,M3,J1,J2,J3)

%    This function was generated by the Symbolic Math Toolbox version 5.4.
%    10-Apr-2011 10:49:23

t690 = alphaF+phi;
t691 = sin(t690);
t692 = cos(t690);
t693 = dalphaF.*lF.*t691;
t694 = dlF.*t691;
t695 = dalphaF.*lF.*t692;
dJFdtTIMESdqdt = [-dalphaF.*(t693-dlF.*t692+dphi.*lF.*t691)+dlF.*(dalphaF.*t692+dphi.*t692)-dphi.*(t693+dphi.*(lF.*t691+l1.*cos(phi))-dlF.*t692);dphi.*(t694+t695+dphi.*(lF.*t692-l1.*sin(phi)))+dlF.*(dalphaF.*t691+dphi.*t691)+dalphaF.*(t694+t695+dphi.*lF.*t692)];
