function cont_pointF = ContactPointF(x,y,phi,alphaF,lF,alphaB,lB,l1,l2,l3,rFoot,g,m1,m2,m3,j1,j2,j3)
%CONTACTPOINTF
%    CONT_POINTF = CONTACTPOINTF(X,Y,PHI,ALPHAF,LF,ALPHAB,LB,L1,L2,L3,RFOOT,G,M1,M2,M3,J1,J2,J3)

%    This function was generated by the Symbolic Math Toolbox version 5.4.
%    10-Apr-2011 10:49:22

t674 = alphaF+phi;
cont_pointF = [x+l1.*cos(phi)+lF.*sin(t674);-rFoot+y-lF.*cos(t674)+l1.*sin(phi)];
