function footPts = FootPtPositions(x,y,phi,alphaF,lF,alphaB,lB,l1,l2,l3,rFoot,g,m1,m2,m3,j1,j2,j3)
%FOOTPTPOSITIONS
%    FOOTPTS = FOOTPTPOSITIONS(X,Y,PHI,ALPHAF,LF,ALPHAB,LB,L1,L2,L3,RFOOT,G,M1,M2,M3,J1,J2,J3)

%    This function was generated by the Symbolic Math Toolbox version 5.4.
%    10-Apr-2011 10:49:24

t724 = cos(phi);
t725 = l1.*t724;
t726 = alphaF+phi;
t727 = alphaB+phi;
t728 = sin(phi);
t729 = l1.*t728;
footPts = reshape([t725+x+lF.*sin(t726),t729+y-lF.*cos(t726),-t725+x+lB.*sin(t727),-t729+y-lB.*cos(t727)],[2, 2]);
