function CoGs = CoGPositions(x,y,phi,alphaF,lF,alphaB,lB,l1,l2,l3,rFoot,g,m1,m2,m3,j1,j2,j3)
%COGPOSITIONS
%    COGS = COGPOSITIONS(X,Y,PHI,ALPHAF,LF,ALPHAB,LB,L1,L2,L3,RFOOT,G,M1,M2,M3,J1,J2,J3)

%    This function was generated by the Symbolic Math Toolbox version 5.4.
%    10-Apr-2011 10:49:23

t704 = alphaF+phi;
t705 = sin(t704);
t706 = cos(phi);
t707 = l1.*t706;
t708 = alphaB+phi;
t709 = sin(t708);
t710 = cos(t704);
t711 = l3-lF;
t712 = sin(phi);
t713 = l1.*t712;
t714 = cos(t708);
t715 = l3-lB;
CoGs = reshape([x,y,phi,t707+x+l2.*t705,t713+y-l2.*t710,t704,t707+x-t705.*t711,t713+y+t710.*t711,t704,-t707+x+l2.*t709,-t713+y-l2.*t714,t708,-t707+x-t709.*t715,-t713+y+t714.*t715,t708],[3, 5]);
