function JF = ContactJacobianF(x,y,phi,alphaF,lF,alphaB,lB,l1,l2,l3,rFoot,g,m1,m2,m3,j1,j2,j3)
%CONTACTJACOBIANF
%    JF = CONTACTJACOBIANF(X,Y,PHI,ALPHAF,LF,ALPHAB,LB,L1,L2,L3,RFOOT,G,M1,M2,M3,J1,J2,J3)

%    This function was generated by the Symbolic Math Toolbox version 5.4.
%    10-Apr-2011 10:49:22

t678 = alphaF+phi;
t679 = cos(t678);
t680 = lF.*t679;
t681 = sin(t678);
t682 = lF.*t681;
JF = reshape([1.0,0.0,0.0,1.0,rFoot+t680-l1.*sin(phi),t682+l1.*cos(phi),rFoot+t680,t682,t681,-t679,0.0,0.0,0.0,0.0],[2, 7]);
