function links = LinkPositions(x,y,phi,alphaF,lF,alphaB,lB,l1,l2,l3,rFoot,g,m1,m2,m3,j1,j2,j3)
%LINKPOSITIONS
%    LINKS = LINKPOSITIONS(X,Y,PHI,ALPHAF,LF,ALPHAB,LB,L1,L2,L3,RFOOT,G,M1,M2,M3,J1,J2,J3)

%    This function was generated by the Symbolic Math Toolbox version 5.4.
%    10-Apr-2011 10:49:24

t717 = cos(phi);
t718 = l1.*t717;
t719 = alphaF+phi;
t720 = sin(phi);
t721 = l1.*t720;
t722 = alphaB+phi;
links = reshape([t718+x+lF.*sin(t719),t721+y-lF.*cos(t719),t718+x,t721+y,-t718+x,-t721+y,-t718+x+lB.*sin(t722),-t721+y-lB.*cos(t722)],[2, 4]);
